language: node_js
node_js:
  - "10"
addons: code_climate
env:
  global:
    - CC_TEST_REPORTER_ID=4a16f35ad676097e7c5c0ec1f1e13d13c48bd57847b2ccf6f12c159275f6551a
cache:
  directories:
    - node_modules
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yarn test --detectOpenHandles -u
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
