export const AUTH = {
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
    ERROR_OCCURRED: 'ERROR_OCCURRED',
  };
export const MENU = {
  ADD_MENU_ITEM: 'ADD_MENU_ITEM',
  GET_MENU: 'GET_MENU',
}  

